//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        public int s_id { get; set; }
        public string name { get; set; }
        public string mobile_number { get; set; }
        public string email_id { get; set; }
        public string password { get; set; }
    }
}
