//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class singuptable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int MobileNo { get; set; }
        public int Password { get; set; }
    }
}
